import {
    arduino,
    cplusplus,
    css,
    cura,
    docker,
    fusion360,
    git,
    html,
    illustrator,
    javascript,
    linux,
    mathematica,
    matlab,
    matplotlib,
    numpy,
    optimumlap,
    proxmox,
    python,
    reactjs,
    solidworks,
    tailwind,
    threejs,
    truenas,
    vscode,
    xd,
} from "../assets";

const skillIcons = [
    { imgURL: solidworks, name: "Solidworks" },
    { imgURL: matlab, name: "MATLAB" },
    { imgURL: cplusplus, name: "C++" },
    { imgURL: python, name: "Python" },
    { imgURL: reactjs, name: "React JS" },
    { imgURL: threejs, name: "Three JS" },
    { imgURL: tailwind, name: "Tailwind" },
    { imgURL: docker, name: "Docker" },
    { imgURL: git, name: "git" },
];

export {skillIcons};